In [1]:
import os
import faiss
import numpy as np
import pandas as pd
import pickle

In [2]:
import tensorflow as tf

from collections import Counter

from tensorflow.keras.models import load_model

from tensorflow.keras.preprocessing.image import (
    load_img,
    img_to_array
)

from tensorflow.keras.applications.resnet50 import (
    preprocess_input
)

from tensorflow.keras.preprocessing.sequence import (
    pad_sequences
)

In [3]:
MODEL_PATH = "../../counterfeit_image_detection/models/embedding_model_finetuned.keras"

EMBEDDINGS_PATH = "../../counterfeit_image_detection/embeddings/shoe_image_embeddings_finetuned_v1.npy"

FILENAMES_PATH = "../../counterfeit_image_detection/embeddings/shoe_image_filenames_v1.npy"

FAISS_PATH = "../../counterfeit_image_detection/embeddings/shoe_faiss_index_v1.index"


METADATA_MAP_PATH = "../../counterfeit_metadata_detection/datasets/authentic_metadata_output.csv"


TEST1_PATH = "../testing/test1_genuine_metadata.csv"

TEST2_PATH = "../testing/test2_genuine_metadata.csv"

TEST3_PATH = "../testing/test3_brand_mismatch.csv"

TEST4_PATH = "../testing/test4_counterfeit_metadata.csv"


SEEN_IMAGES_DIR = "../testing/SeenImages"

UNSEEN_IMAGES_DIR = "../testing/UnseenImages"

In [4]:
class L2Normalize(
    tf.keras.layers.Layer
):
    def call(
        self,
        inputs
    ):
        return tf.math.l2_normalize(
            inputs,
            axis=1
        )


embedding_model = load_model(
    MODEL_PATH,
    custom_objects={
        "L2Normalize": L2Normalize
    },
    compile=False
)

print("Embedding model loaded.")

Embedding model loaded.

In [5]:
image_embeddings = np.load(
    EMBEDDINGS_PATH
)

image_filenames = np.load(
    FILENAMES_PATH,
    allow_pickle=True
)

print(
    "Embedding shape:",
    image_embeddings.shape
)

print(
    "Number of filenames:",
    len(image_filenames)
)

Embedding shape: (1848, 256)
Number of filenames: 1848

In [6]:
image_index = faiss.read_index(
    FAISS_PATH
)

print(
    "Total indexed images:",
    image_index.ntotal
)

Total indexed images: 1848

In [7]:
assert image_index.ntotal == len(image_filenames)

assert image_embeddings.shape[0] == len(image_filenames)

print("FAISS index and embedding files are aligned.")

FAISS index and embedding files are aligned.

In [8]:
metadata_df = pd.read_csv(
    METADATA_MAP_PATH
)

metadata_map = dict(
    zip(
        metadata_df["filename"],
        metadata_df["metadata"]
    )
)

print(
    "Metadata entries:",
    len(metadata_map)
)

Metadata entries: 2642

In [9]:
def extract_brand(text):
    text = str(text).lower()

    if (
        "new balance" in text
        or "newbalance" in text
    ):
        return "newbalance"

    if (
        "under armour" in text
        or "underarmour" in text
    ):
        return "underarmour"

    brands = [
        "nike",
        "puma",
        "vans",
        "reebok"
    ]

    for brand in brands:

        if brand in text:
            return brand

    return "unknown"

In [10]:
def get_embedding(image_path):

    image = load_img(
        image_path,
        target_size=(224, 224)
    )

    image = img_to_array(
        image
    )

    image = preprocess_input(
        image
    )

    image = np.expand_dims(
        image,
        axis=0
    )

    embedding = embedding_model.predict(
        image,
        verbose=0
    )

    return embedding.astype(
        "float32"
    )

In [11]:
def retrieve_similar_images(
    image_path,
    top_k=5
):

    embedding = get_embedding(
        image_path
    )

    faiss.normalize_L2(
        embedding
    )

    similarities, indices = (
        image_index.search(
            embedding,
            top_k
        )
    )

    results = []

    for sim, idx in zip(
        similarities[0],
        indices[0]
    ):

        results.append(
            {
                "filename":
                image_filenames[idx],

                "similarity":
                float(sim)
            }
        )

    return results

In [12]:
metadata_classifier = load_model(
    "../../counterfeit_metadata_detection/models/metadata_counterfeit_classifier_v1.keras",
    compile=False
)

with open(
    "../../counterfeit_metadata_detection/tokenizers/metadata_classifier_tokenizer_v1.pkl",
    "rb"
) as f:
    metadata_tokenizer = pickle.load(f)

print("Metadata classifier loaded.")

Metadata classifier loaded.

In [13]:
MAX_LEN = 110

In [14]:
def get_metadata_score(
    metadata_text
):

    sequence = (
        metadata_tokenizer.texts_to_sequences(
            [metadata_text]
        )
    )

    padded = pad_sequences(
        sequence,
        maxlen=MAX_LEN,
        padding="post"
    )

    prob_fake = float(
        metadata_classifier.predict(
            padded,
            verbose=0
        )[0][0]
    )

    prob_genuine = (
        1.0 - prob_fake
    )

    return prob_genuine

In [15]:
def trust_fusion(
    query_metadata,
    retrieval_results
):

    metadata_score = (
        get_metadata_score(
            query_metadata
        )
    )

    query_brand = extract_brand(
        query_metadata
    )

    retrieved_brands = []

    similarities = []

    for result in retrieval_results:

        similarities.append(
            result["similarity"]
        )

        retrieved_metadata = (
            metadata_map.get(
                result["filename"],
                ""
            )
        )

        retrieved_brand = (
            extract_brand(
                retrieved_metadata
            )
        )

        retrieved_brands.append(
            retrieved_brand
        )

    brand_match_ratio = (
        retrieved_brands.count(
            query_brand
        )
        /
        len(retrieved_brands)
    )

    retrieval_confidence = (
        np.mean(
            similarities
        )
    )

    trust_score = (
        0.50 * metadata_score
        +
        0.35 * brand_match_ratio
        +
        0.15 * retrieval_confidence
    )

    if trust_score >= 0.75:

        prediction = "GENUINE"

    elif trust_score >= 0.50:

        prediction = "SUSPICIOUS"

    else:

        prediction = "LIKELY_COUNTERFEIT"

    return {

        "prediction":
        prediction,

        "trust_score":
        round(
            trust_score,
            4
        ),

        "metadata_score":
        round(
            metadata_score,
            4
        ),

        "brand_match_ratio":
        round(
            brand_match_ratio,
            4
        ),

        "retrieval_confidence":
        round(
            retrieval_confidence,
            4
        ),

        "retrieved_brands":
        retrieved_brands
    }

In [16]:
test1_df = pd.read_csv(
    TEST1_PATH
)

print(
    test1_df.columns
)

test1_df.head()

Index(['filename', 'metadata'], dtype='object')

                   filename                                          metadata
0    normalized_nike_11.jpg  Nike Air Force 1 Low Brown White Casual Sneakers
1   normalized_nike_249.jpg           Nike Dunk Low Red White Casual Sneakers
2  resized_all_vans_129.jpg     Vans Sport Low White Green Orange Skate Shoes
3  resized_all_vans_140.jpg     Vans UltraRange Grey Black Lime Running Shoes
4   resized_all_vans_17.jpg            Vans Sport Low Black White Skate Shoes

In [17]:
results = []

correct = 0

for _, row in test1_df.iterrows():

    image_file = row["filename"]

    query_metadata = row["metadata"]

    image_path = os.path.join(
        SEEN_IMAGES_DIR,
        image_file
    )

    retrieval_results = (
        retrieve_similar_images(
            image_path,
            top_k=5
        )
    )

    fusion_result = trust_fusion(
        query_metadata,
        retrieval_results
    )

    prediction = (
        fusion_result["prediction"]
    )

    is_correct = (
        prediction == "GENUINE"
    )

    if is_correct:
        correct += 1

    results.append(
        {
            "filename":
            image_file,

            "prediction":
            prediction,

            "trust_score":
            fusion_result["trust_score"],

            "metadata_score":
            fusion_result["metadata_score"],

            "brand_match_ratio":
            fusion_result["brand_match_ratio"],

            "retrieval_confidence":
            fusion_result["retrieval_confidence"],

            "correct":
            is_correct
        }
    )

test1_results_df = pd.DataFrame(
    results
)

accuracy = (
    correct /
    len(test1_results_df)
)

print(
    "\nTest 1 Accuracy:",
    round(accuracy, 4)
)

test1_results_df.head(20)

Test 1 Accuracy: 0.9524

,filename,prediction,trust_score,metadata_score,brand_match_ratio,retrieval_confidence,correct
0,normalized_nike_11.jpg,GENUINE,0.9836,1.0,1.0,0.8903,True
1,normalized_nike_249.jpg,GENUINE,0.9682,1.0,1.0,0.7878,True
2,resized_all_vans_129.jpg,SUSPICIOUS,0.6164,1.0,0.0,0.7760,False
3,resized_all_vans_140.jpg,GENUINE,0.9757,1.0,1.0,0.8380,True
4,resized_all_vans_17.jpg,GENUINE,0.9905,1.0,1.0,0.9364,True
5,resized_all_vans_32.jpg,GENUINE,0.9834,1.0,1.0,0.8895,True
6,resized_padded_new_newbalance_2.jpg,GENUINE,0.9813,1.0,1.0,0.8755,True
7,resized_padded_new_newbalance_3.jpg,GENUINE,0.9880,1.0,1.0,0.9197,True
8,resized_padded_new_newbalance_53.jpg,GENUINE,0.9774,1.0,1.0,0.8493,True
9,resized_padded_puma_135.jpg,GENUINE,0.9809,1.0,1.0,0.8726,True
10,resized_padded_puma_33.jpg,GENUINE,0.9728,1.0,1.0,0.8187,True
11,resized_padded_puma_59.jpg,GENUINE,0.9786,1.0,1.0,0.8574,True
12,resized_padded_puma_81.jpg,GENUINE,0.9723,1.0,1.0,0.8150,True
13,resized_padded_reebok_126.jpg,GENUINE,0.9883,1.0,1.0,0.9217,True
14,resized_padded_reebok_22.jpg,GENUINE,0.9776,1.0,1.0,0.8504,True
15,resized_padded_reebok_71.jpg,GENUINE,0.9751,1.0,1.0,0.8337,True
16,resized_padded_reebok_79.jpg,GENUINE,0.9777,1.0,1.0,0.8516,True
17,resized_padded_underarmour_10.jpg,GENUINE,0.9659,1.0,1.0,0.7724,True
18,resized_padded_underarmour_22.jpg,GENUINE,0.9857,1.0,1.0,0.9050,True
19,resized_padded_underarmour_46.jpg,GENUINE,0.9726,1.0,1.0,0.8176,True

In [18]:
test1_failures = test1_results_df[
    test1_results_df["correct"] == False
]

print(
    "\nFailures:",
    len(test1_failures)
)

test1_failures

Failures: 1

,filename,prediction,trust_score,metadata_score,brand_match_ratio,retrieval_confidence,correct
2,resized_all_vans_129.jpg,SUSPICIOUS,0.6164,1.0,0.0,0.776,False

In [19]:
test2_df = pd.read_csv(
    TEST2_PATH
)

print(
    test2_df.shape
)

test2_df.head()

(30, 2)

            filename                                           metadata
0  new balance-1.jpg  New Balance 997 Black Purple Grey Casual Sneakers
1  new balance-2.jpg           New Balance 990 Grey Suede Running Shoes
2  new balance-3.jpg    New Balance 991 Black Grey Purple Running Shoes
3  new balance-4.jpg      New Balance 990 Black Blue Grey Running Shoes
4  new balance-5.jpg    New Balance 550 White Red Black Casual Sneakers

In [20]:
results = []

correct = 0

for _, row in test2_df.iterrows():

    image_file = row["filename"]

    query_metadata = row["metadata"]

    image_path = os.path.join(
        UNSEEN_IMAGES_DIR,
        image_file
    )

    retrieval_results = (
        retrieve_similar_images(
            image_path,
            top_k=5
        )
    )

    fusion_result = trust_fusion(
        query_metadata,
        retrieval_results
    )

    prediction = (
        fusion_result["prediction"]
    )

    is_correct = (
        prediction == "GENUINE"
    )

    if is_correct:
        correct += 1

    results.append(
        {
            "filename":
            image_file,

            "prediction":
            prediction,

            "trust_score":
            fusion_result["trust_score"],

            "metadata_score":
            fusion_result["metadata_score"],

            "brand_match_ratio":
            fusion_result["brand_match_ratio"],

            "retrieval_confidence":
            fusion_result["retrieval_confidence"],

            "retrieved_brands":
            fusion_result["retrieved_brands"],

            "correct":
            is_correct
        }
    )

test2_results_df = pd.DataFrame(
    results
)

accuracy = (
    correct /
    len(test2_results_df)
)

print(
    "\nTest 2 Accuracy:",
    round(accuracy, 4)
)

test2_results_df.head(20)

Test 2 Accuracy: 0.9

,filename,prediction,trust_score,metadata_score,brand_match_ratio,retrieval_confidence,retrieved_brands,correct
0,new balance-1.jpg,GENUINE,0.7568,1.0000,0.4,0.7787,"[vans, vans, vans, newbalance, newbalance]",True
1,new balance-2.jpg,GENUINE,0.9689,1.0000,1.0,0.7929,"[newbalance, newbalance, newbalance, newbalanc...",True
2,new balance-3.jpg,GENUINE,0.8211,1.0000,0.6,0.7407,"[newbalance, newbalance, vans, vans, newbalance]",True
3,new balance-4.jpg,GENUINE,0.9744,1.0000,1.0,0.8295,"[newbalance, newbalance, newbalance, newbalanc...",True
4,new balance-5.jpg,GENUINE,0.8347,1.0000,0.6,0.8311,"[newbalance, vans, vans, newbalance, newbalance]",True
5,nike-1.jpg,GENUINE,0.9618,1.0000,1.0,0.7457,"[nike, nike, nike, nike, nike]",True
6,nike-2.jpg,GENUINE,0.9763,1.0000,1.0,0.8423,"[nike, nike, nike, nike, nike]",True
7,nike-3.jpg,GENUINE,0.9719,1.0000,1.0,0.8129,"[nike, nike, nike, nike, nike]",True
8,nike-4.jpg,GENUINE,0.9587,1.0000,1.0,0.7246,"[nike, nike, nike, nike, nike]",True
9,nike-5.jpg,GENUINE,0.9729,0.9999,1.0,0.8197,"[nike, nike, nike, nike, nike]",True
10,resized_all_vans_721.jpg,GENUINE,0.9758,1.0000,1.0,0.8384,"[vans, vans, vans, vans, vans]",True
11,resized_all_vans_736.jpg,GENUINE,0.9787,1.0000,1.0,0.8582,"[vans, vans, vans, vans, vans]",True
12,resized_padded_puma_172.jpg,GENUINE,0.9711,1.0000,1.0,0.8073,"[puma, puma, puma, puma, puma]",True
13,resized_padded_puma_200.jpg,GENUINE,0.9833,1.0000,1.0,0.8884,"[puma, puma, puma, puma, puma]",True
14,resized_padded_puma_210.jpg,GENUINE,0.9706,1.0000,1.0,0.8038,"[puma, puma, puma, puma, puma]",True
15,resized_padded_puma_211.jpg,SUSPICIOUS,0.6217,1.0000,0.0,0.8113,"[underarmour, underarmour, underarmour, undera...",False
16,resized_padded_puma_214.jpg,GENUINE,0.9803,1.0000,1.0,0.8685,"[puma, puma, puma, puma, puma]",True
17,resized_padded_reebok_156.jpg,SUSPICIOUS,0.6182,1.0000,0.0,0.7877,"[vans, vans, vans, vans, vans]",False
18,resized_padded_reebok_169.jpg,GENUINE,0.9690,1.0000,1.0,0.7930,"[reebok, reebok, reebok, reebok, reebok]",True
19,resized_padded_reebok_172.jpg,GENUINE,0.9762,1.0000,1.0,0.8413,"[reebok, reebok, reebok, reebok, reebok]",True

In [21]:
test2_failures = test2_results_df[
    test2_results_df["correct"] == False
]

print(
    "\nFailures:",
    len(test2_failures)
)

test2_failures

Failures: 3

,filename,prediction,trust_score,metadata_score,brand_match_ratio,retrieval_confidence,retrieved_brands,correct
15,resized_padded_puma_211.jpg,SUSPICIOUS,0.6217,1.0,0.0,0.8113,"[underarmour, underarmour, underarmour, undera...",False
17,resized_padded_reebok_156.jpg,SUSPICIOUS,0.6182,1.0,0.0,0.7877,"[vans, vans, vans, vans, vans]",False
21,resized_padded_reebok_73.jpg,SUSPICIOUS,0.6834,1.0,0.2,0.7563,"[nike, nike, puma, nike, reebok]",False

In [22]:
test3_df = pd.read_csv(
    TEST3_PATH
)

print(
    test3_df.shape
)

test3_df.head()

(30, 2)

            filename                                mismatched_metadata
0  new balance-1.jpg  Nike Air Max 90 Black Purple Grey Casual Sneakers
1  new balance-2.jpg      Puma Suede Classic Grey White Casual Sneakers
2  new balance-3.jpg     ASICS Gel Lyte Black Grey Purple Running Shoes
3  new balance-4.jpg  Reebok Classic Nylon Black Blue Grey Casual Sn...
4  new balance-5.jpg      Nike Dunk Low White Red Black Casual Sneakers

In [23]:
results = []

correct = 0

for _, row in test3_df.iterrows():

    image_file = row["filename"]

    query_metadata = (
        row["mismatched_metadata"]
    )

    image_path = os.path.join(
        UNSEEN_IMAGES_DIR,
        image_file
    )

    retrieval_results = (
        retrieve_similar_images(
            image_path,
            top_k=5
        )
    )

    fusion_result = trust_fusion(
        query_metadata,
        retrieval_results
    )

    prediction = (
        fusion_result["prediction"]
    )

    is_correct = (
        prediction != "GENUINE"
    )

    if is_correct:
        correct += 1

    results.append(
        {
            "filename":
            image_file,

            "prediction":
            prediction,

            "trust_score":
            fusion_result["trust_score"],

            "metadata_score":
            fusion_result["metadata_score"],

            "brand_match_ratio":
            fusion_result["brand_match_ratio"],

            "retrieval_confidence":
            fusion_result["retrieval_confidence"],

            "retrieved_brands":
            fusion_result["retrieved_brands"],

            "correct":
            is_correct
        }
    )

test3_results_df = pd.DataFrame(
    results
)

accuracy = (
    correct /
    len(test3_results_df)
)

print(
    "\nTest 3 Accuracy:",
    round(accuracy, 4)
)

test3_results_df

Test 3 Accuracy: 0.9333

,filename,prediction,trust_score,metadata_score,brand_match_ratio,retrieval_confidence,retrieved_brands,correct
0,new balance-1.jpg,SUSPICIOUS,0.6168,1.000,0.0,0.7787,"[vans, vans, vans, newbalance, newbalance]",True
1,new balance-2.jpg,SUSPICIOUS,0.6189,1.000,0.0,0.7929,"[newbalance, newbalance, newbalance, newbalanc...",True
2,new balance-3.jpg,SUSPICIOUS,0.6111,1.000,0.0,0.7407,"[newbalance, newbalance, vans, vans, newbalance]",True
3,new balance-4.jpg,SUSPICIOUS,0.6244,1.000,0.0,0.8295,"[newbalance, newbalance, newbalance, newbalanc...",True
4,new balance-5.jpg,SUSPICIOUS,0.6247,1.000,0.0,0.8311,"[newbalance, vans, vans, newbalance, newbalance]",True
5,nike-1.jpg,SUSPICIOUS,0.6119,1.000,0.0,0.7457,"[nike, nike, nike, nike, nike]",True
6,nike-2.jpg,SUSPICIOUS,0.6263,1.000,0.0,0.8423,"[nike, nike, nike, nike, nike]",True
7,nike-3.jpg,SUSPICIOUS,0.6219,1.000,0.0,0.8129,"[nike, nike, nike, nike, nike]",True
8,nike-4.jpg,SUSPICIOUS,0.6087,1.000,0.0,0.7246,"[nike, nike, nike, nike, nike]",True
9,nike-5.jpg,SUSPICIOUS,0.6229,1.000,0.0,0.8197,"[nike, nike, nike, nike, nike]",True
10,resized_all_vans_721.jpg,SUSPICIOUS,0.6258,1.000,0.0,0.8384,"[vans, vans, vans, vans, vans]",True
11,resized_all_vans_736.jpg,SUSPICIOUS,0.6287,1.000,0.0,0.8582,"[vans, vans, vans, vans, vans]",True
12,resized_padded_puma_172.jpg,SUSPICIOUS,0.6211,1.000,0.0,0.8073,"[puma, puma, puma, puma, puma]",True
13,resized_padded_puma_200.jpg,SUSPICIOUS,0.6333,1.000,0.0,0.8884,"[puma, puma, puma, puma, puma]",True
14,resized_padded_puma_210.jpg,SUSPICIOUS,0.6206,1.000,0.0,0.8038,"[puma, puma, puma, puma, puma]",True
15,resized_padded_puma_211.jpg,SUSPICIOUS,0.6217,1.000,0.0,0.8113,"[underarmour, underarmour, underarmour, undera...",True
16,resized_padded_puma_214.jpg,SUSPICIOUS,0.6303,1.000,0.0,0.8685,"[puma, puma, puma, puma, puma]",True
17,resized_padded_reebok_156.jpg,GENUINE,0.9682,1.000,1.0,0.7877,"[vans, vans, vans, vans, vans]",False
18,resized_padded_reebok_169.jpg,SUSPICIOUS,0.6190,1.000,0.0,0.7930,"[reebok, reebok, reebok, reebok, reebok]",True
19,resized_padded_reebok_172.jpg,SUSPICIOUS,0.6262,1.000,0.0,0.8413,"[reebok, reebok, reebok, reebok, reebok]",True
20,resized_padded_reebok_174.jpg,SUSPICIOUS,0.6271,1.000,0.0,0.8476,"[reebok, reebok, reebok, reebok, reebok]",True
21,resized_padded_reebok_73.jpg,GENUINE,0.8234,1.000,0.6,0.7563,"[nike, nike, puma, nike, reebok]",False
22,resized_padded_underarmour_10.jpg,SUSPICIOUS,0.6159,1.000,0.0,0.7724,"[underarmour, underarmour, underarmour, undera...",True
23,resized_padded_underarmour_127.jpg,SUSPICIOUS,0.6290,1.000,0.0,0.8598,"[underarmour, underarmour, underarmour, undera...",True
24,resized_padded_underarmour_132.jpg,SUSPICIOUS,0.6291,1.000,0.0,0.8604,"[underarmour, underarmour, underarmour, undera...",True
25,resized_padded_underarmour_138.jpg,SUSPICIOUS,0.6333,1.000,0.0,0.8887,"[underarmour, underarmour, underarmour, undera...",True
26,resized_padded_underarmour_140.jpg,SUSPICIOUS,0.6315,1.000,0.0,0.8766,"[underarmour, underarmour, underarmour, undera...",True
27,resized_padded_vans_310.jpg,SUSPICIOUS,0.6253,0.996,0.0,0.8486,"[vans, vans, vans, vans, vans]",True
28,resized_padded_vans_311.jpg,SUSPICIOUS,0.6354,1.000,0.0,0.9029,"[vans, vans, vans, vans, vans]",True
29,resized_padded_vans_325.jpg,SUSPICIOUS,0.6372,1.000,0.0,0.9149,"[vans, vans, vans, vans, vans]",True

In [24]:
test3_failures = test3_results_df[
    test3_results_df["correct"] == False
]

print(
    "\nFailures:",
    len(test3_failures)
)

test3_failures

Failures: 2

,filename,prediction,trust_score,metadata_score,brand_match_ratio,retrieval_confidence,retrieved_brands,correct
17,resized_padded_reebok_156.jpg,GENUINE,0.9682,1.0,1.0,0.7877,"[vans, vans, vans, vans, vans]",False
21,resized_padded_reebok_73.jpg,GENUINE,0.8234,1.0,0.6,0.7563,"[nike, nike, puma, nike, reebok]",False

In [25]:
test4_df = pd.read_csv(
    TEST4_PATH
)

print(
    test4_df.shape
)

test4_df.head()

(30, 2)

            filename                               counterfeit_metadata
0  new balance-1.jpg  New Balance 997 Black Purple Grey Premium Copy...
1  new balance-2.jpg  New Balance 990 Grey Suede UA Quality Running ...
2  new balance-3.jpg  New Balance 991 Black Grey Purple Imported Cop...
3  new balance-4.jpg  New Balance 990 Black Blue Grey Mirror Quality...
4  new balance-5.jpg  New Balance 550 White Red Black Replica Casual...

In [26]:
results = []

correct = 0

for _, row in test4_df.iterrows():

    image_file = row["filename"]

    query_metadata = (
        row["counterfeit_metadata"]
    )

    image_path = os.path.join(
        UNSEEN_IMAGES_DIR,
        image_file
    )

    retrieval_results = (
        retrieve_similar_images(
            image_path,
            top_k=5
        )
    )

    fusion_result = trust_fusion(
        query_metadata,
        retrieval_results
    )

    prediction = (
        fusion_result["prediction"]
    )

    is_correct = (
        prediction != "GENUINE"
    )

    if is_correct:
        correct += 1

    results.append(
        {
            "filename":
            image_file,

            "prediction":
            prediction,

            "trust_score":
            fusion_result["trust_score"],

            "metadata_score":
            fusion_result["metadata_score"],

            "brand_match_ratio":
            fusion_result["brand_match_ratio"],

            "retrieval_confidence":
            fusion_result["retrieval_confidence"],

            "retrieved_brands":
            fusion_result["retrieved_brands"],

            "correct":
            is_correct
        }
    )

test4_results_df = pd.DataFrame(
    results
)

accuracy = (
    correct /
    len(test4_results_df)
)

print(
    "\nTest 4 Accuracy:",
    round(accuracy, 4)
)

test4_results_df

Test 4 Accuracy: 1.0

,filename,prediction,trust_score,metadata_score,brand_match_ratio,retrieval_confidence,retrieved_brands,correct
0,new balance-1.jpg,LIKELY_COUNTERFEIT,0.2568,0.0000,0.4,0.7787,"[vans, vans, vans, newbalance, newbalance]",True
1,new balance-2.jpg,LIKELY_COUNTERFEIT,0.4693,0.0008,1.0,0.7929,"[newbalance, newbalance, newbalance, newbalanc...",True
2,new balance-3.jpg,LIKELY_COUNTERFEIT,0.3211,0.0000,0.6,0.7407,"[newbalance, newbalance, vans, vans, newbalance]",True
3,new balance-4.jpg,LIKELY_COUNTERFEIT,0.4744,0.0000,1.0,0.8295,"[newbalance, newbalance, newbalance, newbalanc...",True
4,new balance-5.jpg,LIKELY_COUNTERFEIT,0.3350,0.0007,0.6,0.8311,"[newbalance, vans, vans, newbalance, newbalance]",True
5,nike-1.jpg,LIKELY_COUNTERFEIT,0.4619,0.0000,1.0,0.7457,"[nike, nike, nike, nike, nike]",True
6,nike-2.jpg,LIKELY_COUNTERFEIT,0.4770,0.0012,1.0,0.8423,"[nike, nike, nike, nike, nike]",True
7,nike-3.jpg,LIKELY_COUNTERFEIT,0.4719,0.0000,1.0,0.8129,"[nike, nike, nike, nike, nike]",True
8,nike-4.jpg,LIKELY_COUNTERFEIT,0.4587,0.0000,1.0,0.7246,"[nike, nike, nike, nike, nike]",True
9,nike-5.jpg,LIKELY_COUNTERFEIT,0.4730,0.0000,1.0,0.8197,"[nike, nike, nike, nike, nike]",True
10,resized_all_vans_721.jpg,LIKELY_COUNTERFEIT,0.4758,0.0000,1.0,0.8384,"[vans, vans, vans, vans, vans]",True
11,resized_all_vans_736.jpg,LIKELY_COUNTERFEIT,0.4787,0.0000,1.0,0.8582,"[vans, vans, vans, vans, vans]",True
12,resized_padded_puma_172.jpg,SUSPICIOUS,0.5032,0.0643,1.0,0.8073,"[puma, puma, puma, puma, puma]",True
13,resized_padded_puma_200.jpg,LIKELY_COUNTERFEIT,0.4833,0.0000,1.0,0.8884,"[puma, puma, puma, puma, puma]",True
14,resized_padded_puma_210.jpg,LIKELY_COUNTERFEIT,0.4706,0.0000,1.0,0.8038,"[puma, puma, puma, puma, puma]",True
15,resized_padded_puma_211.jpg,SUSPICIOUS,0.5833,0.9232,0.0,0.8113,"[underarmour, underarmour, underarmour, undera...",True
16,resized_padded_puma_214.jpg,LIKELY_COUNTERFEIT,0.4803,0.0000,1.0,0.8685,"[puma, puma, puma, puma, puma]",True
17,resized_padded_reebok_156.jpg,LIKELY_COUNTERFEIT,0.1182,0.0000,0.0,0.7877,"[vans, vans, vans, vans, vans]",True
18,resized_padded_reebok_169.jpg,LIKELY_COUNTERFEIT,0.4779,0.0180,1.0,0.7930,"[reebok, reebok, reebok, reebok, reebok]",True
19,resized_padded_reebok_172.jpg,LIKELY_COUNTERFEIT,0.4762,0.0000,1.0,0.8413,"[reebok, reebok, reebok, reebok, reebok]",True
20,resized_padded_reebok_174.jpg,LIKELY_COUNTERFEIT,0.4771,0.0000,1.0,0.8476,"[reebok, reebok, reebok, reebok, reebok]",True
21,resized_padded_reebok_73.jpg,LIKELY_COUNTERFEIT,0.1834,0.0000,0.2,0.7563,"[nike, nike, puma, nike, reebok]",True
22,resized_padded_underarmour_10.jpg,LIKELY_COUNTERFEIT,0.4659,0.0000,1.0,0.7724,"[underarmour, underarmour, underarmour, undera...",True
23,resized_padded_underarmour_127.jpg,LIKELY_COUNTERFEIT,0.4874,0.0168,1.0,0.8598,"[underarmour, underarmour, underarmour, undera...",True
24,resized_padded_underarmour_132.jpg,LIKELY_COUNTERFEIT,0.4791,0.0000,1.0,0.8604,"[underarmour, underarmour, underarmour, undera...",True
25,resized_padded_underarmour_138.jpg,LIKELY_COUNTERFEIT,0.4833,0.0000,1.0,0.8887,"[underarmour, underarmour, underarmour, undera...",True
26,resized_padded_underarmour_140.jpg,LIKELY_COUNTERFEIT,0.4815,0.0000,1.0,0.8766,"[underarmour, underarmour, underarmour, undera...",True
27,resized_padded_vans_310.jpg,LIKELY_COUNTERFEIT,0.4773,0.0000,1.0,0.8486,"[vans, vans, vans, vans, vans]",True
28,resized_padded_vans_311.jpg,LIKELY_COUNTERFEIT,0.4879,0.0049,1.0,0.9029,"[vans, vans, vans, vans, vans]",True
29,resized_padded_vans_325.jpg,LIKELY_COUNTERFEIT,0.4872,0.0000,1.0,0.9149,"[vans, vans, vans, vans, vans]",True

In [27]:
test4_failures = test4_results_df[
    test4_results_df["correct"] == False
]

print(
    "\nFailures:",
    len(test4_failures)
)

test4_failures

Failures: 0

Empty DataFrame
Columns: [filename, prediction, trust_score, metadata_score, brand_match_ratio, retrieval_confidence, retrieved_brands, correct]
Index: []

In [31]:
summary = pd.DataFrame({

    "Scenario": [
        "Seen + Genuine Metadata",
        "Unseen + Genuine Metadata",
        "Unseen + Brand Mismatch",
        "Unseen + Counterfeit Metadata"
    ],

    "Accuracy": [
        test1_results_df["correct"].mean(),
        test2_results_df["correct"].mean(),
        test3_results_df["correct"].mean(),
        test4_results_df["correct"].mean()
    ],

    "Avg Trust": [
        test1_results_df["trust_score"].mean(),
        test2_results_df["trust_score"].mean(),
        test3_results_df["trust_score"].mean(),
        test4_results_df["trust_score"].mean()
    ],

    "Avg Metadata Score": [
        test1_results_df["metadata_score"].mean(),
        test2_results_df["metadata_score"].mean(),
        test3_results_df["metadata_score"].mean(),
        test4_results_df["metadata_score"].mean()
    ],

    "Avg Brand Match": [
        test1_results_df["brand_match_ratio"].mean(),
        test2_results_df["brand_match_ratio"].mean(),
        test3_results_df["brand_match_ratio"].mean(),
        test4_results_df["brand_match_ratio"].mean()
    ],

    "Avg Retrieval Confidence": [
        test1_results_df["retrieval_confidence"].mean(),
        test2_results_df["retrieval_confidence"].mean(),
        test3_results_df["retrieval_confidence"].mean(),
        test4_results_df["retrieval_confidence"].mean()
    ]
})

summary.round(4)

,Scenario,Accuracy,Avg Trust,Avg Metadata Score,Avg Brand Match,Avg Retrieval Confidence
0,Seen + Genuine Metadata,0.9524,0.9613,1.0000,0.9524,0.8533
1,Unseen + Genuine Metadata,0.9000,0.9247,1.0000,0.8600,0.8248
2,Unseen + Brand Mismatch,0.9333,0.6423,0.9999,0.0533,0.8248
3,Unseen + Counterfeit Metadata,1.0000,0.4419,0.0343,0.8600,0.8248

In [30]:
for name, df in [
    ("Test 1", test1_results_df),
    ("Test 2", test2_results_df),
    ("Test 3", test3_results_df),
    ("Test 4", test4_results_df)
]:
    
    print("\n", name)
    print(df["prediction"].value_counts())

 Test 1
prediction
GENUINE       20
SUSPICIOUS     1
Name: count, dtype: int64

 Test 2
prediction
GENUINE       27
SUSPICIOUS     3
Name: count, dtype: int64

 Test 3
prediction
SUSPICIOUS    28
GENUINE        2
Name: count, dtype: int64

 Test 4
prediction
LIKELY_COUNTERFEIT    28
SUSPICIOUS             2
Name: count, dtype: int64